=== creator83/etml/catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <!-- определение простых элементов -->
   <xs:element name="name-category" type="xs:string"/>
   <xs:element name="name-sub-category" type="xs:string"/>
   <xs:element name="name-item" type="xs:string"/>
   <xs:element name="pic" type="xs:string"/>
   <xs:element name="price" type="xs:decimal"/>
   
   <!-- определение составных элементов -->
   <xs:element name="category">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="name-category"/>
            <xs:element ref="sub-category"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="sub-category">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="name-sub-category"/>
            <xs:element ref="item"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   
   <xs:element name="item">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="name-item"/>
            <xs:element ref="pic"/>
			<xs:element ref="price"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>   
   
   <xs:element name="catalog">
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="category"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element> 
   
</xs:schema>

=== creator83/etml/catalog.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<catalog
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="catalog.xsd">
	<category>
		<name-category>Фильтры</name-category>
		<sub-category>
			<name-sub-category>пункт1</name-sub-category>
			<item>
				<name-item>элемент1</name-item>
				<pic>/img</pic>
				<price>1200</price>
			</item>
			<item>
				<name-item>элемент2</name-item>
				<pic>/img</pic>
				<price>1200</price>
			</item>
		</sub-category>
		<sub-category>
			<name-sub-category>пункт2</name-sub-category>
			<item>
				<name-item>элемент1</name-item>
				<pic>/img</pic>
				<price>1200</price>
			</item>
			<item>
				<name-item>элемент2</name-item>
				<pic>/img</pic>
				<price>1200</price>
			</item>
		</sub-category>
	</category>
	<category>
		<name-category>Деаэраторы</name-category>
		<sub-category>
			<name-sub-category>пункт1</name-sub-category>
			<item>
				<name-item>подпункт1</name-item>
				<pic>/img</pic>
				<price>4200</price>
			</item>
		</sub-category>
	</category>
</catalog>
